title: MESIN KASIR
author: 
  name: mesinkasir
  email: hockeycorpmarketing@gmail.com
  whatsapp: 6285646104747
  phone: 62895339403223
  address: Ruko Pasar Wisata Juanda Q.05-07
  country: Sidoarjo - East Java - Indonesia
  map: https://goo.gl/maps/EpcU3m3ryPMihifx7
description: > # this means to ignore newlines until "show_excerpts:"
  Mesin kasir toko minimarket supermarket.
  Mesin kasir restoran cafe kuliner.
  Mesin kasir online.
cover: /assets/img/APLIKASI MESIN KASIR ONLINE.png
show_excerpts: false # set to true to show excerpts on the homepage
future: true
url: https://mesinkasir.github.io

minima:
  date_format: "%-d %b, %Y"

home:
  desc: Mesin kasir toko minimarket supermarket. Mesin kasir restoran cafe kuliner. Mesin kasir online.
  title: Mesin Kasir
  cover: assets/img/online%20kasir.webp
  description: Solusi kebutuhan pos point of sale set mu.
  content: Temukan kemudahan dan mobile dengan menggunakan mesin kasir online maupun offline desktop mode modern device terminal pos kami.
  title1: MODERN POS TERBARU.
  content1: Menggunakan all in one touchscreen technology menjadikan kesempurnaan dalam bekerja dan mudah dalam integrasi dengan hardware device untuk digunakan dengan barcode system maupun full touchscreen metode. Material desain mewah slim fashionable stylish. 
  title2: REAL POINT OF SALE.
  content2: Dukungan hardware terbaik dengan OS windows untuk kesempurnaan dan kestabilan dan mempercepat transaksi kasir anda. Kemudahan dalam integrasi dengan berbagai peralatan kasir hardware pos device semakin lebih baik , dan kini saat nya update upgrade pos system dengan package ini.
  title3: PEFORMA MAKSIMAL.
  content3: Powerfull dengan kestabilan system digunakan, dan super maksimal dengan terminal ini untuk digunakan, super sensitif touchscreen layar sentuh semakin membuat kasir lebih cepat untuk bertransaksi dengan one touch system.
  title4: MULTI DEVICE INTEGRATION.
  content4: Dengan berbagai multi port di dalam nya, menjadikan nya lebih mudah dalam kebutuhan untuk integrasi dengan berbagai hardware dan peralatan kasir untuk digunakan, dengan tujuan agar lebih mudah dalam satu terminal pos ini untuk bekerja dengan printer kasir, laser barcode, mesin barcode dan berbagai perangkat lain menyempurnakan konsep all in one pos system.Pastikan memilih POS set yang tepat dalam kebutuhan mu untuk kestabilan kecepatan dan kesempurnaan dalam pencatatan pembukuan plus transaksi kasir dengan paket ini. 
  url4: https://github.com/mesinkasir/mesinkasir.github.io/raw/main/e-catalog/TOUCHSCREEN%20POS.pdf
  title5: MINIMARKET TOKO.
  content5: Solusi terbaik dengan konsep dan khusus untuk minimarket dan toko shop store dengan berbagai fitur lengkap digunakan, penjnualan kasir bergambar, pembayaran dengan gambar mata uang , multi pembayaran, e-catalog , barcode label untuk di tempel pada produk dan rak display, laporan inventori stok, laporan member pelanggan, laporan penjualan, laporan pendapatan detail, dan laba rugi serta lain nya. support dengan single standalone maupun untuk membagi dengan divisi stok, kasir, admin.
  url5: https://github.com/mesinkasir/mesinkasir.github.io/raw/main/e-catalog/CHROMPOS%20retail%20shop.pdf
  title6: KULINER RESTORAN CAFE RUMAH MAKAN.
  content6: Special untuk usaha kuliner dengan kebutuhan penjualan via fastfood penjualan kasir langsung maupun untuk kebutuhan dengan pembagian divisi waiters, kitchen , kasir, admin. menyempurnakan dalam bekerja dengan pos resto cafe rumah makan kuliner ini, plus fitur pemilihan menu, menu penjualan bergambar, menu resep , laporan detail , laba rugi dan lain lain siap untuk menunjang kebutuhan lengkap usaha kuliner , dan support web app clouds databased untuk memudahkan owner cek laporan via smartphone nya.
  url6: https://github.com/mesinkasir/mesinkasir.github.io/raw/main/e-catalog/unipos-%20%20next%20level%20resto%20cafe%20system.pdf
  title7: WEB APP.
  content7: Kebutuhan untuk web app hadir sebagai optional full online metode, dengan website untuk usaha dan bisnis include dengan aplikasi online.
  title8: APK Android.
  content8: Sempurnakan dengan APK android dalam bekerja sebagai optional APK untuk kebutuhan terbaik backend dan frontend.
  title9: HUBUNGI KAMI.
  content9: Hubungi kami untuk konsultasi dan informasi terminal device pos ini.
  url91: /oldschool
  url92: /blog
  url93: /start.html
  title91: Oldschool
  title92: Blog
  title93: Get Start

# ganti kalau mau push repo github
# theme: minima
theme: dablogger

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
